### ISSUE TITLE
Bug: Fehler bei HTTPS

### ISSUE THREAD

**Issue by zonky2** [MacGyer/ytvideo#1]
im Template ist die URL fix auf http eingestellt - läuft die (Haupt)Seite auf https kommt es zu einer Blockierung (bei den meisten Browsern) - da Google generell auf https setzt, kann das m.E. generell auf https geändert werden; ansonsten die Sache abfragen...

**Comment by MacGyer** [comment]
fixed in https://github.com/MacGyer/ytvideo/commit/5af794384b384f6435ed0213cda351808dd3739c

**Comment by zonky2** [comment]
Danke!
